/*
 * This source file was generated by the Gradle 'init' task
 */
package jpi.p4;

public class App {

    public static void main(String[] args) {
        // == OOP · Object's n' Classes == 
        // Exercise01.run();
        Exercise02.run();
    }
}
