/*
 * This source file was generated by the Gradle 'init' task
 */
package jpi.p4t1;

public class App {

    public static void main(String[] args) {
        // == OOP · Object's n' Classes == 
        // Exercise01.run();
        // Exercise02.run();
        Exercise03.run();
        // Exercise04.run();
        // Exercise05.run();
        // Exercise06.run();
        // Exercise07.run(); 
        // Exercise08.run();
        // Exercise09.run();
        Exercise10.run();
        Exercise11.run();
    }
}
