/*
 * This source file was generated by the Gradle 'init' task
 */
package jpi.p5t2;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        App app = new App();
        assertNotNull(app);
    }
}
